### ISSUE TITLE
Issues with Transparent Textures

### ISSUE THREAD

**Issue by Naudi0** [Reforged333/Sodium-Reloaded#6] opened 2022-01-28 07:11 UTC
Hi! I added this port to the mod pack that I'm working on and I'm receiving kind of an odd issue. The transparent textures on the plants from the mods Oh The Biomes You'll Go and Cyclic are appearing as black and white instead of transparent. I removed Sodium Reloaded from the mod pack and the textures went back to normal, but I really need Sodium for the pack to run smoothly. Is this something that can be fixed or is it a compatibility issue that cannot?

Thanks for working on this port! It's been a really big life saver!

**Comment by KKotik** [comment] 2022-01-28 08:02
Duplicate of #2, as dev stated will be fixed in next version.

**Comment by Reforged333** [comment] 2022-01-28 15:08
Duplicate of #2  and #4  which is fixed in the coming version.
thanks.

**Closed by Reforged333** 2022-01-28 15:08 UTC
