### ISSUE TITLE
Incompatibility with some connected textures.

### ISSUE THREAD

**Issue by Atlantispy** [Reforged333/Sodium-Reloaded#4] opened 2022-01-27 20:15 UTC
Most notable example is Create mod, causing their pillars to not work correctly.

**Comment by Ztritsval** [comment] 2022-01-28 09:51
The same goes to the Immersive Engineering and Farmers Delight 
![Base Profile Screenshot 2022 01 27 - 17 36 11 91](https://user-images.githubusercontent.com/98527369/151525373-cf33d55b-abd7-4511-a025-02a8f9b6f598.png)

**Comment by KKotik** [comment] 2022-01-28 14:23
The thing that @Ztritsval mentioned is duplicate of #2 and it is already fixed indev, in next release that will be fixed. The issue itself with create and connected texture is different one and the one that really exist.

**Comment by Reforged333** [comment] 2022-01-28 15:09
Duplicate of #2 and #6  which is fixed in the coming version.
thanks.

**Closed by Reforged333** 2022-01-28 15:09 UTC
